version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "aperam"
      POSTGRES_PASSWORD: "aperam"
      POSTGRES_DB: "aperam"
    ports:
      - "5432:5432"
    volumes:
      - .docker/db:/var/lib/postgresql/data
    networks:
      - db-network
  redis:
    image: redislabs/redismod:latest
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - .docker/cache:/data



networks: 
 db-network:
    driver: bridge