version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "aperam"
      MYSQL_DATABASE: "aperam"
    ports:
      - "3307:3306"
    volumes:
      - .docker/db:/var/lib/mysql
    networks:
      - db-network

networks: 
 db-network:
    driver: bridge